service: afex-backend-test
useDotenv: true
plugins:
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-dynamodb-local

functions:
  app: 
    handler: dist/main.handler
    events:
      - http:
          method: any
          path: /{any+}

provider: 
    name: aws
    runtime: nodejs14.x
    stage: ${opt:stage, 'dev'}
    region: 'us-east-1'
    timeout: 30
    apiGateway:
      shouldStartNameWithService: true

    environment: 
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
      NODE_OPTIONS: --enable-source-maps --stack-trace-limit=1000
      DYNAMODB_ENDPOINT: ${self:custom.endpoints.dynamodbURL}
    iam: 
      role: 
        statements: 
            - Effect: 'Allow'
              Action: 
                - 'dynamodb:DescribeTable'
                - 'dynamodb:Query'
                - 'dynamodb:Scan'
                - 'dynamodb:GetItem'
                - 'dynamodb:PutItem'
                - 'dynamodb:UpdateItem'
                - 'dynamodb:DeleteItem'

              Resource:
                - arn:aws:dynamodb:us-east-1:159972493637:table/alumnos

custom: 
  optimize:
    external: ['swagger-ui-dist']
  esbuild: 
    bundle: true
    minify: false
    sourcemap: true
    exclude: aws-sdk
    target: node14
    define: 'require.resolve: undefined'
    platform: node
    concurrency: 10

  dynamodb: 
    start: 
      port: 8000
      inMemory: false
      noStart: true
      dbPath: '$HOME/Descargas/dynamodb_local_latest/DynamoDBLocal.jar'
      sharedDb: true

    stages: dev
  endpoints:
    dynamodbURL: 'http://localhost:8000'

resources: 
    Resources: 
      alumnos: 
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: alumnos
          AttributeDefinitions: 
              - AttributeName: RUT
                AttributeType: S

              - AttributeName: PROFILE
                AttributeType: S

          KeySchema: 
              - AttributeName: RUT
                KeyType: HASH
                
              - AttributeName: PROFILE
                KeyType: RANGE

          ProvisionedThroughput: 
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1